
spring: 
  datasource: 
    url: jdbc:mysql://192.168.129.16:3306/tfhyfw?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tfkj123
    type: com.alibaba.druid.pool.DruidDataSource
    default-auto-commit: false
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 20
      maxActive: 5000
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  main: 
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 192.168.129.16
    port: 6379
    password: tfkj123
    timeout: 5000
    pool:
      max-active: 1000
      max-wait: 300000
      max-idle: 200
      min-idle: 0
      testOnBorrow: true
      testOnReturn: true
      

#这里是用于扫描xml文件的，和datasourceConfig中的@MapperScan配置不冲突      
mybatis: 
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: com.tfjk.modules
  
netty: 
  bossThreadCount: 200
  workerThreadCount: 200
  tcp-port: 9091
  keepAlive: true
  backlog: 100
 
server: 
  port: 8081
  contextPath: /
  error: 
    path: /system/error
  tomcat: 
    uri-encoding: UTF-8
    max-threads: 1000