# spring.datasource.url用于自动配置时(会使用我的druid连接池)，如果自己使用DataSourceConfig.java中的方法手动配置时(使用默认的连接管理池HikariConfig)，则需要使用jdbc-url，好像前者到tomcat上貌似抛出因连接未关闭而内存泄露的错误
spring: 
  datasource: 
    url: jdbc:mysql://39.98.237.227:3309/sevenbo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: sevenbo
    password: Abcd@1234
    type: com.alibaba.druid.pool.DruidDataSource
    default-auto-commit: false
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 20
      maxActive: 5000
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
  main: 
    allow-bean-definition-overriding: true
  jpa: 
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl: 
          auto: none
  mvc: 
    static-path-pattern: /image/**
  resources: 
    static-locations: classpath:/images/      

#druid: 
#  # 下面为连接池的补充设置，应用到上面所有数据源中
#  #连接池相关配置
#  initial-size: 2
#  min-idle: 1
#  maxActive: 10
#  # 配置获取连接等待超时的时间
#  max-wait: 60000
#  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#  timeBetweenEvictionRunsMillis: 60000
#  # 配置一个连接在池中最小生存的时间，单位是毫秒
#  minEvictableIdleTimeMillis: 300000
#  validationQuery: SELECT 1 FROM DUAL
#  testWhileIdle: true
#  testOnBorrow: false
#  testOnReturn: false
#  # 打开PSCache，并且指定每个连接上PSCache的大小
#  poolPreparedStatements: false
#  maxPoolPreparedStatementPerConnectionSize: 20
#  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#  filters: stat,wall,log4j
#  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  # 合并多个DruidDataSource的监控数据
#  useGlobalDataSourceStat: true

#这里是用于扫描xml文件的，和datasourceConfig中的@MapperScan配置不冲突      
mybatis: 
  config-locations: mybatis/mybatis-config.xml
  mapper-locations: cn/roilat/biz/*/mappers/*Mapper.xml
  type-aliases-package: cn.roilat.biz.blog.model
  
server: 
  port: 8081
  contextPath: /
  error: 
    path: /system/error
  tomcat: 
    uri-encoding: UTF-8
    max-threads: 1000