l#DTYW_CBSB
BZ#varchar#200#null#DTYW_CBSB
DQSBBZ#char#1#not mull#DTYW_CBSB
YXQ#datetime#8#null#DTYW_CBSB
HXCS#smallint#2#null#DTYW_CBSB
ECCBZ#char#1#not mull#DTYW_CBSB
HWPS#int#4#null#DTYW_CBSB
HWZL#decimal#8#null#DTYW_CBSB
TSHWBZ#char#1#null#DTYW_CBSB
QLBZ#char#1#null#DTYW_CBSB
LRRYDM#char#11#null#DTYW_CBSB
JGDM#char#6#not mull#DTYW_CBSB
CZSJ#datetime#8#null#DTYW_CBSB
CZYDM#char#11#null#DTYW_CBSB
GXBZ#char#1#not mull#DTYW_CBSB
MRUT#datetime#8#not mull#DTYW_CBSB
XXLY#char#7#not mull#DTYW_CBSB
CBBH#char#20#not mull#DTYW_CBJBXX_XGCY_del0507
CYZSHM#varchar#20#not mull#DTYW_CBJBXX_XGCY_del0507
CYXM#varchar#20#not mull#DTYW_CBJBXX_XGCY_del0507
SRZWDM#varchar#2#null#DTYW_CBJBXX_XGCY_del0507
JGDM#char#6#not mull#DTYW_CBJBXX_XGCY_del0507
CZSJ#datetime#8#not mull#DTYW_CBJBXX_XGCY_del0507
CZYDM#char#11#not mull#DTYW_CBJBXX_XGCY_del0507
GXBZ#char#1#not mull#DTYW_CBJBXX_XGCY_del0507
MRUT#datetime#8#not mull#DTYW_CBJBXX_XGCY_del0507
XXLY#char#7#not mull#DTYW_CBJBXX_XGCY_del0507
SFZHM#varchar#18#null#DTYW_CBJBXX_XGCY_del0507
ZSZWDM#varchar#2#null#DTYW_CBJBXX_XGCY_del0507
ZSZWMC#varchar#40#null#DTYW_CBJBXX_XGCY_del0507
JZBZ#char#1#not mull#DTYW_CBJBXX_XGCY_del0507
NF#char#4#not mull#DTYW_BB_MAXSHIP
YF#char#2#not mull#DTYW_BB_MAXSHIP
JCGBZ#char#1#not mull#DTYW_BB_MAXSHIP
BGBZ#char#1#not mull#DTYW_BB_MAXSHIP
JGDM#char#6#not mull#DTYW_BB_MAXSHIP
KHBZ#char#1#not mull#DTYW_BB_MAXSHIP
QZSXH#char#26#not mull#DTYW_BB_MAXSHIP
ZWCM#nvarchar#80#null#DTYW_BB_MAXSHIP
GJ#nvarchar#30#null#DTYW_BB_MAXSHIP
ZD#decimal#8#null#DTYW_BB_MAXSHIP
QC#decimal#8#null#DTYW_BB_MAXSHIP
CS#decimal#8#null#DTYW_BB_MAXSHIP
DGRQ#datetime#8#null#DTYW_BB_MAXSHIP
GXBZ#char#1#not mull#DTYW_BB_MAXSHIP
MRUT#datetime#8#not mull#DTYW_BB_MAXSHIP
SPBZ#char#1#not mull#DTYW_BB_MAXSHIP
ID#char#11#not mull#DTYW_RBAC_MMYXQ
YXQ#datetime#8#null#DTYW_RBAC_MMYXQ
DWBH#char#7#not mull#DTYW_FWRZYDWBA_SNP_
FLAG_#char#1#not mull#DTYW_FWRZYDWBA_SNP_
BRIEF_#varchar#10#null#DTYW_FWRZYDWBA_SNP_
MODITIME_#varchar#15#null#DTYW_FWRZYDWBA_SNP_
LOCK_#int#4#not mull#DTYW_FWRZYDWBA_SNP_
RWYWBH#char#23#not mull#DTYW_YTHRWXCJC
RWZLDM#char#6#not mull#DTYW_YTHRWXCJC
RWZLMC#char#60#null#DTYW_YTHRWXCJC
RWYY#char#30#null#DTYW_YTHRWXCJC
BZ#varchar#255#null#DTYW_YTHRWXCJC
CJSJ#datetime#8#not mull#DTYW_YTHRWXCJC
CJRYDM#char#11#not mull#DTYW_YTHRWXCJC
JGDM#char#6#not mull#DTYW_YTHRWXCJC
CZSJ#datetime#8#not mull#DTYW_YTHRWXCJC
CZYDM#char#11#not mull#DTYW_YTHRWXCJC
GXBZ#char#1#not mull#DTYW_YTHRWXCJC
MRUT#datetime#8#not mull#DTYW_YTHRWXCJC
XXLY#char#7#not mull#DTYW_YTHRWXCJC
NAME#varchar#50#not mull#HT_DESTIN
NODE#varchar#50#not mull#HT_DESTIN
SEND#int#4#not mull#HT_DESTIN
WRITE#int#4#not mull#HT_DESTIN
FIRST#int#4#null#HT_DESTIN
YSSPH#char#23#not mull#DTTW_FWRZXYS_SP_SNP_
FLAG_#char#1#not mull#DTTW_FWRZXYS_SP_SNP_
BRIEF_#varchar#10#null#DTTW_FWRZXYS_SP_SNP_
MODITIME_#varchar#15#null#DTTW_FWRZXYS_SP_SNP_
LOCK_#int#4#not mull#DTTW_FWRZXYS_SP_SNP_
SBXH#varchar#26#not mull#DTYW_DZSB_CYJZX
JCGBZ#char#1#not mull#DTYW_DZSB_CYJZX
DZXH#int#4#not mull#DTYW_DZSB_CYJZX
JZXXH#int#4#not mull#DTYW_DZSB_CYJZX
JZXZLDM#char#3#null#DTYW_DZSB_CYJZX
KXSL#int#4#null#DTYW_DZSB_CYJZX
ZXSL#int#4#null#DTYW_DZSB_CYJZX
GXBZ#char#1#not mull#DTYW_DZSB_CYJZX
MRUT#datetime#8#not mull#DTYW_DZSB_CYJZX
XXLY#char#7#null#DTYW_DZSB_CYJZX
ZYBH#char#23#not mull#DTYW_FWRZYTJCL
TJCLDM#char#7#not mull#DTYW_FWRZYTJCL
TJCLMC#varchar#255#not mull#DTYW_FWRZYTJCL
XMDM#char#4#not mull#DTYW_FWRZYTJCL
SBBZ#char#1#not mull#DTYW_FWRZYTJCL
SHBZ#char#1#not mull#DTYW_FWRZYTJCL
BZ#varchar#255#null#DTYW_FWRZYTJCL
GXBZ#char#1#not mull#DTYW_FWRZYTJCL
MRUT#datetime#8#not mull#DTYW_FWRZYTJCL
XXLY#char#7#not mull#DTYW_FWRZYTJCL
SBDBH#char#18#null#DZSB_CZ_CBSBGT_HW
BSXH#tinyint#1#not mull#DZSB_CZ_CBSBGT_HW
XH#int#4#not mull#DZSB_CZ_CBSBGT_HW
WHSBDBH#char#18#null#DZSB_CZ_CBSBGT_HW
THDH#varchar#100#null#DZSB_CZ_CBSBGT_HW
HWLX#char#1#not mull#DZSB_CZ_CBSBGT_HW
WGXH#char#10#null#DZSB_CZ_CBSBGT_HW
WGBH#char#10#null#DZSB_CZ_CBSBGT_HW
ZQYSMCZW#varchar#160#null#DZSB_CZ_CBSBGT_HW
ZQYSMCYW#varchar#255#null#DZSB_CZ_CBSBGT_HW
WXLB#char#10#null#DZSB_CZ_CBSBGT_HW
ZYXS#varchar#20#null#DZSB_CZ_CBSBGT_HW
JS#int#4#null#DZSB_CZ_CBSBGT_HW
BJZL#char#20#null#DZSB_CZ_CBSBGT_HW
ZZL#decimal#8#null#DZSB_CZ_CBSBGT_HW
ZHGZWMC#varchar#40#null#DZSB_CZ_CBSBGT_HW
ZHGYWMC#varchar#80#null#DZSB_CZ_CBSBGT_HW
XHGZWMC#varchar#40#null#DZSB_CZ_CBSBGT_HW
XHGYWMC#varchar#80#null#DZSB_CZ_CBSBGT_HW
ZZWZ#varchar#255#null#DZSB_CZ_CBSBGT_HW
BZXGG#varchar#30#null#DZSB_CZ_CBSBGT_HW
JZX20#int#4#null#DZSB_CZ_CBSBGT_HW
JZX30#int#4#null#DZSB_CZ_CBSBGT_HW
JZX40#int#4#null#DZSB_CZ_CBSBGT_HW
JZX45#int#4#null#DZSB_CZ_CBSBGT_HW
BZXTEU#decimal#5#null#DZSB_CZ_CBSBGT_HW
FBZXGG#int#4#null#DZSB_CZ_CBSBGT_HW
FBXXS#int#4#null#DZSB_CZ_CBSBGT_HW
GGCC#varchar#30#null#DZSB_CZ_CBSBGT_HW
GGSL#int#4#null#DZSB_CZ_CBSBGT_HW
TYR#varchar#60#null#DZSB_CZ_CBSBGT_HW
HZ#varchar#60#null#DZSB_CZ_CBSBGT_HW
TSHWBZ#char#1#null#DZSB_CZ_CBSBGT_HW
PXBZ#char#1#null#DZSB_CZ_CBSBGT_HW
SHRDM#char#11#null#DZSB_CZ_CBSBGT_HW
SHRQ#datetime#8#null#DZSB_CZ_CBSBGT_HW
SHYJ#varchar#255#null#DZSB_CZ_CBSBGT_HW
LZBZ#char#1#not mull#DZSB_CZ_CBSBGT_HW
BZ#varchar#80#null#DZSB_CZ_CBSBGT_HW
ZHBZ#char#1#null#DZSB_CZ_CBSBGT_HW
JCGBZ#char#1#not mull#DZSB_CZ_CBSBGT_HW
SBXH#varchar#29#not mull#DZSB_CZ_CBSBGT_HW
SJLY#char#3#not mull#DZSB_CZ_CBSBGT_HW
BJCL#char#1#null#DZSB_CZ_CBSBGT_HW
ID#char#11#not mull#RBAC_USER_SNP_
FLAG_#char#1#not mull#RBAC_USER_SNP_
BRIEF_#varchar#10#null#RBAC_USER_SNP_
MODITIME_#varchar#15#null#RBAC_USER_SNP_
LOCK_#int#4#not mull#RBAC_USER_SNP_
ID#char#16#not mull#RBAC_ACCESS_LOG
GROUPID#char#6#null#RBAC_ACCESS_LOG
USERID#char#11#null#RBAC_ACCESS_LOG
PERMISSIONID#char#11#null#RBAC_ACCESS_LOG
ACCESSDATE#varchar#20#null#RBAC_ACCESS_LOG
URI#varchar#255#null#RBAC_ACCESS_LOG
HOST#varchar#255#null#RBAC_ACCESS_LOG
ADDR#varchar#40#null#RBAC_ACCESS_LOG
TYPE#varchar#10#null#RBAC_ACCESS_LOG
DESCRIPTION#text#16#null#RBAC_ACCESS_LOG
RWYWBH#char#23#not mull#DTYW_YTHRWXX
RWBH#char#13#not mull#DTYW_YTHRWXX
YWBH#char#23#null#DTYW_YTHRWXX
ZYLY#char#10#null#DTYW_YTHRWXX
ZYBH#char#29#null#DTYW_YTHRWXX
RWLYDM#char#8#not mull#DTYW_YTHRWXX
RWMS#varchar#120#null#DTYW_YTHRWXX
RWZL#varchar#200#null#DTYW_YTHRWXX
DWMC#varchar#80#null#DTYW_YTHRWXX
CBBH#varchar#20#null#DTYW_YTHRWXX
CBMC#varchar#40#null#DTYW_YTHRWXX
QSBWDM#char#7#null#DTYW_YTHRWXX
ZZBWDM#char#7#null#DTYW_YTHRWXX
QSWZ#varchar#60#null#DTYW_YTHRWXX
ZZWZ#varchar#60#null#DTYW_YTHRWXX
LXR#char#20#null#DTYW_YTHRWXX
LXDH#char#11#null#DTYW_YTHRWXX
YJKSSJ#datetime#8#null#DTYW_YTHRWXX
YJJSSJ#datetime#8#null#DTYW_YTHRWXX
CSYJ#varchar#200#null#DTYW_YTHRWXX
FSYJ#varchar#200#null#DTYW_YTHRWXX
ZGRY#varchar#20#null#DTYW_YTHRWXX
SPBBH#varchar#20#null#DTYW_YTHRWXX
ZFRYDM#char#11#null#DTYW_YTH